server:
  port: 8081

#数据库连接信息
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_generator?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

#mybatis配置
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath:com/**/mapper/*.xml
